export const Logo = "https://clipdle.tv/clipdle.png";

export const Hero = "https://th.bing.com/th/id/OIP.6ZAGyQqK9RsylXZpwPbx-wHaES?pid=ImgDet&rs=1";

export const intro = "Welcome to a cinematic journey like no other! Our movie review website is your ultimate destination for insightful, engaging, and thought-provoking critiques of the latest blockbusters, hidden gems, and timeless classics. Whether you're a die-hard cinephile or simply looking for a captivating film to watch, our reviews offer a blend of analysis, emotion, and storytelling that will enrich your movie-watching experience. Join us as we delve into the magical world of cinema, where every frame is a canvas of imagination and every story has the power to touch our hearts and minds."


export const Movies = [
  {
    "id": "0",
    "image": "https://channelmyanmar.org/wp-content/uploads/2023/08/MV5BOWY3Yjk2ZGItODFkZC00YzM0LWJjOWMtZjZlNmFiNGE0NGFmXkEyXkFqcGdeQXVyMTQyNDk2NzE@._V1_-139x200.jpg",
    "title": "Let Love Grow (2023)",
    "type": "Drama, Family, Romance",
    "cast": {
              "director": "Damián Romay and Demi Castro",
              "actor": "Britton Webb",
              "actress": "Jennifer Bonner",
            },
    "synopsis": "Let Love Grow (2023) is a heartwarming romantic drama that blooms with emotion, captivating performances, and breathtaking visuals. The film follows Sarah, a woman seeking purpose, who discovers love and self-discovery in a charming flower farm. With its relatable themes and enchanting storytelling, Let Love Grow is a cinematic gem that reminds us to embrace love and nurture our dreams. Don't miss this captivating journey of growth and resilience.",
    "rating": "6.0",
    "trailer": "https://youtu.be/ICea9dI1onE",
    "url": "https://channelmyanmar.org/let-love-grow-2023/",
  },
  {
    "id": "1",
    "image": "https://image.tmdb.org/t/p/w185/gVPw9gRPsZZhzY6cIXp6h6nep5M.jpg",
    "title": "Epic Tails (2023)",
    "type": "Adventure, Animation, Family, Fantasy",
    "cast": {
              "director": "",
              "actor": "Aloïs Le Labourier Tiêu",
              "actress": "Arthur Raynal",
            },
    "synopsis": "Epic Tails (2023) is a delightful film filled with heart and adventure. Its captivating storytelling and lovable characters make it an enjoyable watch for all ages. A fun-filled cinematic experience that leaves a lasting impression.",
    "rating": "5.9",
    "trailer": "https://youtu.be/BH0rkCQjTfI",
    "url": "https://channelmyanmar.org/epic-tails-2023/",
  },
  {
    "id": "2",
    "image": "https://channelmyanmar.org/wp-content/uploads/2023/08/MV5BZjRkY2VkODctOGY4NS00MTY3LThkOTMtMTk4Yzc5ODkxYmI4XkEyXkFqcGdeQXVyMTU3MjY0NDI4._V1_.jpg",
    "title": "Madhi (2023)",
    "type": "Bollywood, Musical",
    "cast": {
              "director": "Naga Dhanush",
              "actor": "Sreeram Nimmala",
              "actress": "Vikram Veramaneni",
            },
    "synopsis": "Madhi (2023) is a gripping and intense film that takes viewers on an emotional rollercoaster. With powerful performances and a compelling storyline, it leaves a lasting impact. A must-watch for fans of intense drama.",
    "rating": "9.3",
    "trailer": "https://youtu.be/PJeYIYy1eLQ",
    "url": "https://channelmyanmar.org/madhi-2023/",
  },
  {
    "id": "3",
    "image": "https://channelmyanmar.org/wp-content/uploads/2023/08/FvUVt3hXgAAxP1H.jpg",
    "title": "Oppenheimer (2023)",
    "type": " Biography, Drama, History",
    "cast": {
              "director": "Christopher Nolan",
              "actor": "Adam Kroeger",
              "actress": "Alden Ehrenreich",
            },
    "synopsis": "Oppenheimer (2023) is a masterful biographical drama that delves into the life of J. Robert Oppenheimer, the brilliant mind behind the atomic bomb. With exceptional storytelling and stellar performances, it offers a thought-provoking and immersive cinematic experience. A must-watch for history enthusiasts and fans of compelling biopics.",
    "rating": "8.7",
    "trailer": "https://youtu.be/bK6ldnjE3Y0",
    "url": "https://channelmyanmar.org/oppenheimer-2023/",
  },
  {
    "id": "4",
    "image": "https://image.tmdb.org/t/p/w185/yxpBM3KXaB1ejWn00TbihD9ph8L.jpg",
    "title": "Godless: The Eastfield Exorcism (2023)",
    "type": " Horror",
    "cast": {
              "director": "Nick Kozakis",
              "actor": "Dan Ewing",
              "actress": "Eliza Matengu",
            },
    "synopsis": "Godless: The Eastfield Exorcism (2023) is a bone-chilling horror film that will keep you on the edge of your seat. With its eerie atmosphere and terrifying visuals, it delivers a hair-raising experience. A must-see for horror aficionados seeking a thrilling and haunting ride.",
    "rating": "6.3",
    "trailer": "https://youtu.be/r_DKxCl7AXU",
    "url": "https://channelmyanmar.org/godless-the-eastfield-exorcism-2023/",
  },
  {
    "id": "5",
    "image": "https://channelmyanmar.org/wp-content/uploads/2023/08/MV5BNmExZDBmYTEtYTM1Mi00MTRiLWFjNjYtMzU1NjMzMTAxMGRlXkEyXkFqcGdeQXVyNjgxNzE1MDk@._V1_-scaled.jpg",
    "title": "Bhaag Saale (2023)",
    "type": "Bollywood, Comedy, Crime",
    "cast": {
              "director": "",
              "actor": "",
              "actress": "",
            },
    "synopsis": "Bhaag Saale (2023) is an exhilarating roller coaster ride that will keep you on the edge of your seat from start to finish. This must-watch thriller boasts a compelling storyline, strong performances, and superb direction. The gripping plot follows a man who finds himself trapped in a web of deceit and danger, with every twist and turn leaving the audience guessing. The narrative is masterfully executed, leaving no room for boredom or predictability. The talented cast delivers powerful performances, bringing the characters to life and making you emotionally invested in their journey. The adrenaline-pumping action sequences and stunning cinematography further enhance the cinematic experience. Overall, Bhaag Saale is a perfect blend of suspense, drama, and thrilling moments that will leave you wanting for more. Don't miss out on this gripping thriller - Bhaag Saale is definitely a movie worth watching!",
    "rating": "7.0",
    "trailer": "https://youtu.be/2IB4p6G6TW4",
    "url": "https://channelmyanmar.org/bhaag-saale-2023/",
  },
  {
    "id": "6",
    "image": "https://image.tmdb.org/t/p/w185/boUwVljEdNJxIqn2gnO4d5BkUHE.jpg",
    "title": "Fatafati (2023)",
    "type": "Bollywood, Drama, Uncategorized",
    "cast": {
              "director": "Aritra Mukherjee",
              "actor": "Abir Chatterjee",
              "actress": "Asmee Ghosh",
            },
    "synopsis": "Fatafati (2023) is a delightful and entertaining movie that brings a burst of energy to the screen. This feel-good film takes you on a joyous ride, filled with laughter, catchy music, and vibrant dance sequences. The talented cast delivers captivating performances, keeping you engaged throughout the story. With its lighthearted plot and energetic atmosphere, Fatafati is a perfect choice for those looking for a fun and uplifting cinematic experience. Sit back, relax, and let this movie tickle your funny bone and leave you with a smile on your face. Fatafati is a true treat for the senses and promises to brighten up your day!",
    "rating": "7.5",
    "trailer": "https://youtu.be/c6Lf4vN4b1Q",
    "url": "https://channelmyanmar.org/fatafati-2023/",
  },
  {
    "id": "7",
    "image": "https://channelmyanmar.org/wp-content/uploads/2023/08/MV5BN2FlNjAyYjktODYyNC00OTBkLTkxMmUtZGI4NmUyM2I0MzMyXkEyXkFqcGdeQXVyMTY1MzAyNjU4._V1_.jpg",
    "title": "Kolai (2023)",
    "type": " Action, Bollywood, Crime, Thriller",
    "cast": {
              "director": "Balaji K. Kumar",
              "actor": "Anand",
              "actress": "Arjun Chidambaram",
            },
    "synopsis": "Kolai (2023) is a gripping and intense thriller that will keep you on the edge of your seat. With its well-crafted storyline and strong performances, this movie takes you on a dark and unsettling journey. The film's narrative is intricately woven, leaving you guessing at every turn and building up to a shocking finale. The impressive cinematography and haunting score further enhance the ominous atmosphere of the film. The talented cast deliver powerful performances, successfully conveying the raw emotions and complexities of their characters. Kolai is a must-watch for anyone seeking a mind-bending and immersive cinematic experience that will leave you with chills long after the credits roll.",
    "rating": "7.0",
    "trailer": "https://youtu.be/B_h5D-JEZts",
    "url": "https://channelmyanmar.org/kolai-2023/",
  },
  {
    "id": "8",
    "image": "https://channelmyanmar.org/wp-content/uploads/2023/08/MV5BZDk5YzcyZjktZGFjMi00YTI4LTlhYjUtZjE5NDAzNDdhODRmXkEyXkFqcGdeQXVyMTQ3Mzk2MDg4._V1_.jpg",
    "title": "Pareshan (2023)",
    "type": "Bollywood, Comedy",
    "cast": {
              "director": "Rupak Ronaldson",
              "actor": "Pavani Karanam",
              "actress": "Thiruveer",
            },
    "synopsis": "Pareshan (2023) is a heartwarming and relatable film that explores the struggles of everyday life with great depth and sincerity. The movie captures the essence of the human experience, showcasing the complexities of relationships, aspirations, and self-discovery. With its realistic portrayal of characters and their emotional journeys, Pareshan tugs at your heartstrings and makes you reflect on your own life. The beautifully crafted narrative is complemented by stellar performances from the talented cast, who bring authenticity and vulnerability to their roles. This movie is a poignant reminder that it's okay to feel lost and overwhelmed at times, and that there is always hope and resilience amidst the chaos. Pareshan is a must-watch for anyone seeking a touching and thought-provoking cinematic experience that will resonate long after the credits roll.",
    "rating": "6.5",
    "trailer": "https://youtu.be/Rh8_isGdF3g",
    "url": "https://channelmyanmar.org/pareshan-2023/",
  },
  {
    "id": "9",
    "image": "https://image.tmdb.org/t/p/w185/tWd9lw09AsaBpCXYCYyaBxs7UIn.jpg",
    "title": "Ramon (2023)",
    "type": "Action, Comedy",
    "cast": {
              "director": "Jesús del Cerro",
              "actor": "Alexandru Ion",
              "actress": "Ana-Maria Calița",
            },
    "synopsis": "Ramon is a kind person, he tries to do good things, but he is making them much worse. He is looking for that special person and ends up in Bucharest, were troubles are following him.",
    "rating": "7",
    "trailer": "https://youtu.be/2QxRwrsHbNQ",
    "url": "https://channelmyanmar.org/ramon-2023/",
  },
  {
    "id": "10",
    "image": "https://channelmyanmar.org/wp-content/uploads/2023/08/MV5BNTAyOWZmMzMtYzUxYy00NGExLWJmODYtYzU1NzViNDcxNGM4XkEyXkFqcGdeQXVyODY2MTUxMDA@._V1_.jpg",
    "title": "Kutch Express (2023)",
    "type": "Bollywood, Drama, Family",
    "cast": {
              "director": "Viral Shah",
              "actor": "Bhumika Barot",
              "actress": "Darsheel Safary",
            },
    "synopsis": "Kutch Express (2023) is a gripping and captivating film that takes you on an exhilarating journey through the enchanting landscapes of Kutch. The movie seamlessly blends elements of drama, adventure, and romance, making it a truly engaging cinematic experience. The visuals are breathtaking, capturing the raw beauty of the desert and the vibrant culture of the region. The story unfolds at a perfect pace, keeping you hooked with its twists and turns. The performances by the talented cast are commendable, especially the lead actors who bring depth and authenticity to their characters. With its rich storytelling and stunning cinematography, Kutch Express is a must-watch for movie enthusiasts and travel lovers alike.",
    "rating": "6.7",
    "trailer": "https://youtu.be/26B24vrYmCY",
    "url": "https://channelmyanmar.org/kutch-express-2023/",
  },
  {
    "id": "11",
    "image": "https://channelmyanmar.org/wp-content/uploads/2022/07/lightyear.png",
    "title": "Lightyear (2022)",
    "type": "Action, Adventure, Animation",
    "cast": {
              "director": "Angus MacLane",
              "actor": "Angus MacLane",
              "actress": "Arthur Ortiz",
            },
    "synopsis": "Lightyear (2022) is a visually stunning and thrilling space adventure that takes viewers on an extraordinary journey beyond our imagination. As a prequel to the beloved Toy Story franchise, this movie explores the origin story of Buzz Lightyear, the iconic astronaut toy. The animation is top-notch, with breathtakingly realistic visuals that transport the audience into the vastness of outer space. The action-packed storyline keeps you on the edge of your seat, filled with intense space battles and heart-pounding moments. The voice acting, led by the talented Chris Evans, brings depth and charm to the characters, adding an emotional layer to the film. Lightyear is a captivating and nostalgic adventure that will leave audiences of all ages in awe of the limitless possibilities of the universe.",
    "rating": "5.3",
    "trailer": "https://youtu.be/BwPL0Md_QFQ",
    "url": "https://channelmyanmar.org/lightyear-2022/",
  },
  {
    "id": "12",
    "image": "https://www.themoviedb.org/t/p/original/vbIsAHenb9F1SGfeSIhOoWI7gyK.jpg",
    "title": "Scooby-Doo! And Krypto, Too! (2023)",
    "type": "Action, Animation, Comedy",
    "cast": {
              "director": "Cecilia Aranovich",
              "actor": "Diedrich Bader",
              "actress": "Frank Welker",
            },
    "synopsis": "Scooby-Doo! And Krypto, Too! (2023) is a delightful and fun-filled animated crossover that brings together beloved characters from two iconic franchises - Scooby-Doo and Krypto the Superdog. This entertaining film combines mystery-solving and superhero adventures, creating a unique and exciting storyline. The animated visuals are vibrant and engaging, capturing the spirit of both worlds perfectly. The voice acting is excellent, with the familiar and talented cast delivering their performances with enthusiasm. With its humorous moments, clever plot twists, and heartwarming friendships, Scooby-Doo! And Krypto, Too! is a must-watch for fans of both franchises, providing a nostalgic and enjoyable experience for viewers of all ages.",
    "rating": "7",
    "trailer": "https://youtu.be/6NfkdZThS4I",
    "url": "https://channelmyanmar.org/scooby-doo-and-krypto-too-2023/",
  },
  {
    "id": "13",
    "image": "https://channelmyanmar.org/wp-content/uploads/2015/10/MV5BOTgxMDQwMDk0OF5BMl5BanBnXkFtZTgwNjU5OTg2NDE@._V1_SY1000_CR006741000_AL_.jpg",
    "title": "Inside Out (2015)",
    "type": "Animation",
    "cast": {
              "director": "Pete Docter",
              "actor": "Amy Poehler",
              "actress": "Bill Hader",
            },
    "synopsis": "Inside Out (2015) is a heartwarming and thought-provoking animated film that takes viewers on a journey through the depths of human emotions. The movie brilliantly explores the inner workings of the human mind, personifying emotions like joy, sadness, anger, fear, and disgust as quirky and relatable characters. This imaginative concept allows the audience to gain a deep understanding of the complexities of human emotions and the importance of embracing all emotions. The storytelling is beautifully crafted, seamlessly balancing humor and emotional depth. The animation is stunning, with vibrant and imaginative visuals that bring the inner world to life. With its engaging plot, powerful messages, and memorable characters, Inside Out is not just a great animated film, but also a valuable exploration of the human experience.",
    "rating": "8.2",
    "trailer": "https://youtu.be/yRUAzGQ3nSY",
    "url": "https://channelmyanmar.org/inside-out-2015/",
  },
  {
    "id": "14",
    "image": "https://image.tmdb.org/t/p/w185/A7mK52WGXKwbEGEj8MApzaYnSiC.jpg",
    "title": "Hello (2017)",
    "type": "Action, Bollywood, Romance",
    "cast": {
              "director": "Vikram Kumar",
              "actor": "Ajay",
              "actress": "Akhil Akkineni",
            },
    "synopsis": "Hello (2017) is a heartwarming and charming romantic film that will leave you smiling from start to finish. The movie tells the tale of two people who are destined to meet and fall in love, overcoming obstacles and misunderstandings along the way. With its beautiful cinematography and picturesque locations, Hello creates a visually appealing backdrop for the unfolding love story. The performances by the lead actors are stellar, bringing depth and relatability to their characters. The music is another highlight of the film, with soulful melodies that perfectly capture the emotions of the story. Hello is a feel-good movie that reminds us of the power of love and the magic that can happen when two souls connect.",
    "rating": "7",
    "trailer": "https://youtu.be/6WgnE6J07e8",
    "url": "https://channelmyanmar.org/hello-2017/",
  },
  {
    "id": "15",
    "image": "https://channelmyanmar.org/wp-content/uploads/2018/12/272714R1.jpg",
    "title": "Hello Guru Prema Kosame (2018)",
    "type": "Bollywood, Comedy, Drama, Romance",
    "cast": {
              "director": "Trinadha Rao Nakkina",
              "actor": "Anupama Parameswaran",
              "actress": "Prakash Raj",
            },
    "synopsis": "Hello Guru Prema Kosame (2018) is a light-hearted romantic comedy that entertains with its charming storyline and lovable characters. The movie revolves around a young man who moves to the city with dreams of success and falls in love with his landlord's daughter. The film captures the essence and beauty of small-town life while exploring the themes of love, family, and ambition. The performances by the lead actors are impressive, with chemistry that crackles on-screen. The music is also delightful, with catchy songs that capture the mood of the film. Hello Guru Prema Kosame is a fun and enjoyable movie that will have you laughing, crying, and rooting for the protagonists until the very end.",
    "rating": "7.1",
    "trailer": "https://youtu.be/QIpWbcdxdqk",
    "url": "https://channelmyanmar.org/hello-guru-prema-kosame-2018/",
  },
  {
    "id": "16",
    "image": "https://image.tmdb.org/t/p/w185/5353SqWG4xlTVs1YLk1OzmGMdOg.jpg",
    "title": "Hero (2019)",
    "type": "Action, Bollywood, Drama, Thriller",
    "cast": {
              "director": "Abhay Deol",
              "actor": "Abhay Deol",
              "actress": "Arjun Sarja",
            },
    "synopsis": "Hero (2019) is an action-packed thriller that will keep you on the edge of your seat from start to finish. The movie centers around a vigilante who takes justice into his own hands to protect the city from crime and corruption. With its gripping storyline and suspenseful moments, Hero offers a thrilling ride filled with unexpected twists and turns. The action sequences are well-choreographed and visually stunning, adding to the excitement of the film. The performances by the lead actors are commendable, with their intensity and charisma driving the narrative forward. Hero is a thrilling and adrenaline-fueled movie that action movie lovers will thoroughly enjoy.",
    "rating": "6.7",
    "trailer": "https://youtu.be/5FZnvzAA2iQ",
    "url": "https://channelmyanmar.org/hero-2019/",
  },
  {
    "id": "17",
    "image": "https://image.tmdb.org/t/p/w185/rY6fScdYUBgGDcMcZsIDPgX0Hvj.jpg",
    "title": "Mr. Majnu (2019)",
    "type": "Uncategorized",
    "cast": {
              "director": "P. Sathish Chandra, Venky Atluri",
              "actor": "Akhil Akkineni",
              "actress": "Anisha Mandhara",
            },
    "synopsis": "Mr. Majnu (2019) is a delightful romantic comedy that leaves audiences with a warm and fuzzy feeling. Akhil Akkineni shines as the charismatic playboy, Vikram, who finds himself in a whirlwind of emotions when he meets the strong-willed and independent Nikitha, played brilliantly by Nidhhi Agerwal. The film's engaging storyline keeps you hooked from start to finish, striking a perfect balance between lighthearted humor and heartfelt moments. The chemistry between the lead pair is undeniable, making their on-screen romance a joy to watch. The music by Thaman S adds to the film's charm, enhancing the emotional depth of the story. Although some parts may feel familiar, the overall execution and the stellar performances by the cast make Mr. Majnu a thoroughly enjoyable watch for anyone in the mood for a heartwarming romantic flick.",
    "rating": "6.7",
    "trailer": "https://youtu.be/XSnFa0zqXRM",
    "url": "https://channelmyanmar.org/mr-majnu-2019/",
  },
  {
    "id": "18",
    "image": "https://channelmyanmar.org/wp-content/uploads/2019/06/tholi-prema-poster.jpg",
    "title": "Tholi Prema (2018)",
    "type": "Romance",
    "cast": {
              "director": "Venky Atluri",
              "actor": "Priyadarshi Pullikonda",
              "actress": "Raashi Khanna",
            },
    "synopsis": "Tholi Prema (2018) is an enchanting romantic drama that strikes all the right chords. Varun Tej's portrayal of Aditya, a young man deeply entangled in the complexities of love, is both endearing and relatable. Raashi Khanna's performance as Varsha, his love interest, adds a perfect blend of innocence and depth to the story. The film beautifully captures the journey of their relationship, from the exhilarating highs of first love to the poignant lows of separation. Director Venky Atluri weaves a compelling narrative, skillfully balancing the tender moments with lively humor and engaging dialogues. The music by S. Thaman adds an enchanting dimension to the film, making it an emotionally resonant experience. Tholi Prema is an absolute treat for romance enthusiasts, delivering a heartwarming tale of love, destiny, and the timeless beauty of relationships.",
    "rating": "7.3",
    "trailer": "https://youtu.be/gDBz7Oq_lRI",
    "url": "https://channelmyanmar.org/tholi-prema-2018/",
  },
  {
    "id": "19",
    "image": "https://image.tmdb.org/t/p/w185/1T5BAF0RsrQfQik5WtXA30gJlk7.jpg",
    "title": "Annaatthe (2021)",
    "type": "Action, Bollywood, Drama",
    "cast": {
              "director": "Siva",
              "actor": "Jagapati Babu",
              "actress": "Keerthy Suresh",
            },
    "synopsis": "Annaatthe (2021) is a captivating and action-packed Tamil film that brings together an ensemble cast led by the legendary Rajinikanth. The film showcases the power of relationships and camaraderie as it delves into the life of its protagonist. Rajinikanth's charismatic presence and stellar performance anchor the movie, while the supporting cast adds depth and charm to the narrative. The film's engaging plot, coupled with impressive action sequences and well-executed emotional moments, keeps the audience thoroughly entertained. Director Siva's deft storytelling, combined with the pulsating music and remarkable visuals, creates an immersive cinematic experience. Annaatthe pays homage to the quintessential Rajinikanth style while offering a refreshing and enjoyable ride for fans and moviegoers alike.",
    "rating": "4.7",
    "trailer": "https://youtu.be/zyVX8g71TGo",
    "url": "https://channelmyanmar.org/annaatthe-2021/",
  },
  {
    "id": "20",
    "image": "https://channelmyanmar.org/wp-content/uploads/2020/06/81Syf7T4HQL._AC_SL1500_.jpg",
    "title": "Battleship (2012)",
    "type": "Action, Adventure, Sci-Fi",
    "cast": {
              "director": "Peter Berg",
              "actor": "Alexander Skarsgård",
              "actress": " Brooklyn Decker",
            },
    "synopsis": "Battleship (2012) is a visually spectacular science fiction action film that delivers a mix of intense naval warfare and extraterrestrial conflict. The movie boasts impressive special effects and exhilarating battle sequences that keep viewers on the edge of their seats. While the plot may lean on familiar tropes, the cast, including Taylor Kitsch, Liam Neeson, and Rihanna, injects energy and charisma into their roles. The film's combination of high-octane action, human perseverance, and a touch of humor make it an enjoyable popcorn flick. Director Peter Berg orchestrates a symphony of explosions and suspense, providing a thrilling cinematic experience. While not groundbreaking, Battleship offers a dose of blockbuster entertainment for fans of action-packed extravaganzas.",
    "rating": "5.8",
    "trailer": "https://youtu.be/JpoabtbEJOI",
    "url": "https://channelmyanmar.org/battleship-2012/",
  },
  {
    "id": "21",
    "image": "https://channelmyanmar.org/wp-content/uploads/2018/03/pacific-rim-poster-1.jpg",
    "title": "Pacific Rim (2013)",
    "type": "Action, Adventure, Sci-Fi",
    "cast": {
              "director": "Dug Rotstein, Guillermo del Toro, Shane B. Scott",
              "actor": "Burn Gorman",
              "actress": "Charlie Day",
            },
    "synopsis": "Pacific Rim (2013) is an exhilarating and visually stunning sci-fi film that celebrates the sheer excitement of giant robot battles against monstrous creatures from another dimension. Directed by Guillermo del Toro, the movie combines awe-inspiring special effects, captivating world-building, and a diverse cast led by Charlie Hunnam and Idris Elba. The concept of human-piloted mechs facing off against colossal kaiju is executed with a sense of grandeur and flair that captures the audience's imagination. While character development occasionally takes a backseat to the action, the film's heart lies in the camaraderie and determination of its heroes. With epic battles, a strong thematic core, and a touch of del Toro's signature style, Pacific Rim delivers a thrilling cinematic ride for fans of both sci-fi and monster genres.",
    "rating": "6.9",
    "trailer": "https://youtu.be/5guMumPFBag",
    "url": "https://channelmyanmar.org/pacific-rim-2013/",
  },
  {
    "id": "22",
    "image": "https://channelmyanmar.org/wp-content/uploads/2018/06/pacific-rim-uprising-poster-1.jpg",
    "title": "Pacific Rim: Uprising (2018)",
    "type": "Action, Adventure, Sci-Fi",
    "cast": {
              "director": "Kristin Voumard, Melina Burns, Nick Satriano, Steven S. DeKnight",
              "actor": "Adria Arjona",
              "actress": " Burn Gorman",
            },
    "synopsis": "Pacific Rim: Uprising (2018) continues the larger-than-life spectacle of its predecessor, delivering even more colossal robot vs. monster battles. While lacking the visionary touch of Guillermo del Toro, the film offers a fun and action-packed experience with John Boyega leading the charge. The plot leans towards the predictable, focusing on new characters and challenges, yet it manages to capture the essence of camaraderie and heroism. The visual effects are impressive, and the fast-paced action keeps the audience engaged. Though it might not reach the heights of the original, Pacific Rim: Uprising still provides an entertaining dose of futuristic battles and epic showdowns.",
    "rating": "5.6",
    "trailer": "https://youtu.be/fUjicxMPDzs",
    "url": "https://channelmyanmar.org/pacific-rim-uprising-2018-blu-ray-1080p-5-1-ch-x264/",
  },
  {
    "id": "23",
    "image": "https://channelmyanmar.org/wp-content/uploads/2022/12/MV5BN2U3OTJjNzYtMjUwZC00ZmViLTk0MjgtMDNkNzJiYjdmMDQ3XkEyXkFqcGdeQXVyMTA3MDk2NDg2._V1_.jpg",
    "title": "Thank God (2022)",
    "type": "Bollywood, Comedy, Fantasy",
    "cast": {
              "director": "Indra Kumar",
              "actor": "Ajay Devgn",
              "actress": "Kanwaljit Singh",
            },
    "synopsis": "Thank God (2022) is a lighthearted and humorous Indian comedy that brings together an ensemble cast to explore the theme of second chances. The film follows the story of three individuals who find themselves in unexpected situations and are given an opportunity to rectify their past mistakes. With a mix of witty dialogues and situational comedy, the movie keeps the audience entertained throughout. Ajay Devgn, Sidharth Malhotra, and Rakul Preet Singh deliver enjoyable performances, adding charm to the narrative. While the plot might tread familiar territory, the film's comedic timing and feel-good moments make it a pleasant watch for those seeking a dose of laughter and positivity.",
    "rating": "6.1",
    "trailer": "https://youtu.be/x-sgnhYJGOA",
    "url": "https://channelmyanmar.org/thank-god-2022/",
  },
  {
    "id": "24",
    "image": "https://image.tmdb.org/t/p/w185/6UNHOWGOrXv8rlH3OFOMLjmQZgu.jpg",
    "title": "Wish Dragon (2021)",
    "type": "Adventure, Animation, Comedy",
    "cast": {
              "director": "Chris Appelhans",
              "actor": "Alexandre Chen",
              "actress": "Bobby Lee",
            },
    "synopsis": "Wish Dragon (2021) is a heartwarming and imaginative animated film that offers a modern twist on the classic tale of wishes and friendship. The movie follows the journey of Din, a young man who discovers a magical dragon capable of granting wishes. As he navigates his desires and learns life lessons, the film skillfully weaves together humor, adventure, and touching moments. The animation is vibrant and captivating, with the voice talents of Jimmy Wong and John Cho adding depth to their characters. While the narrative might echo familiar themes, Wish Dragon manages to carve its own identity through its creative storytelling and charming execution, making it a delightful watch for audiences of all ages.",
    "rating": "7.4",
    "trailer": "https://youtu.be/uWIRyU5fuzU",
    "url": "https://channelmyanmar.org/wish-dragon-2021/",
  },
  {
    "id": "25",
    "image": "https://image.tmdb.org/t/p/w185/paZRSPyrG611PVDQEcu9JZkwBZZ.jpg",
    "title": "The Bravest (2019)",
    "type": "Action, Drama",
    "cast": {
              "director": "Tony Chan",
              "actor": "Du Jiang, Huang Xiaoming",
              "actress": "Jason Koo",
            },
    "synopsis": "The Bravest (2019) is a gripping and emotional Chinese disaster film that pays tribute to the courage and dedication of firefighters in the face of overwhelming challenges. Based on real events, the movie depicts the heroic efforts of a group of firefighters as they battle a massive fire in a skyscraper. The film effectively captures the intensity of the situations, showcasing both the physical and emotional toll on the characters. With impressive visuals and intense action sequences, The Bravest keeps the audience engaged while highlighting the sacrifices made by these first responders. Although some characters and plot elements might feel familiar, the film's authentic portrayal of bravery and selflessness makes it a moving and memorable tribute to those who risk their lives to protect others.",
    "rating": "7.3",
    "trailer": "https://youtu.be/RNhhK4inRrw",
    "url": "https://channelmyanmar.org/the-bravest2019/",
  },
  {
    "id": "26",
    "image": "https://image.tmdb.org/t/p/w185/tegQNllG9HfRWexDIkK8wMwC6ce.jpg",
    "title": "Total Dhamaal (2019)",
    "type": "Action, Adult, Bollywood, Comedy",
    "cast": {
              "director": "Amit Singh Rajput, Apoorva Tripathi",
              "actor": "Ajay Devgn, Anil Kapoor",
              "actress": "Jaffrey, Madhuri Dixit",
            },
    "synopsis": "Total Dhamaal (2019) is a madcap Indian comedy that delivers a roller-coaster ride of laughter and chaos. The film takes audiences on a wild adventure as a group of eccentric characters embark on a treasure hunt filled with outrageous obstacles and hilarious mishaps. The ensemble cast, featuring Anil Kapoor, Madhuri Dixit, and Ajay Devgn, brings energy and comedic timing to their roles. While the plot may lean towards the absurd, the film's slapstick humor, witty one-liners, and over-the-top situations keep the entertainment quotient high. Director Indra Kumar's knack for comedy shines through as he orchestrates the comedic chaos. Total Dhamaal might not be a cinematic masterpiece, but it certainly delivers on its promise of delivering non-stop laughs and entertainment for those seeking a light-hearted, laughter-filled experience.",
    "rating": "4.7",
    "trailer": "https://youtu.be/fo9EhcwQXcM",
    "url": "https://channelmyanmar.org/total-dhamaal-2019/",
  },
  {
    "id": "27",
    "image": "https://image.tmdb.org/t/p/w185/nQZJK8ApcqjkHs7IE3ybQudBz8J.jpg",
    "title": "Mission Mangal(2019)",
    "type": "Drama, History",
    "cast": {
              "director": "Amogh Shet, Asha Dhingra",
              "actor": "Akshay Kumar",
              "actress": "Daniel O'Kane",
            },
    "synopsis": "Mission Mangal (2019) is an inspiring and well-crafted Indian space drama that brings to life the remarkable story of the Mars Orbiter Mission by the Indian Space Research Organisation (ISRO). The film skillfully blends scientific achievement with human emotion, depicting the challenges faced by a diverse team of scientists as they work tirelessly to launch India's first interplanetary mission. Led by Vidya Balan, Akshay Kumar, and an ensemble cast, the performances are sincere and relatable. While some cinematic liberties are taken, the film successfully captures the spirit of determination, innovation, and teamwork that led to the mission's success. Director Jagan Shakti balances technical details with personal narratives, making Mission Mangal not only informative but also emotionally resonant. The film's patriotic undertones and celebration of scientific achievement make it a must-watch for anyone interested in a compelling blend of human stories and India's technological advancement.",
    "rating": "6.6",
    "trailer": "https://youtu.be/q10nfS9V090",
    "url": "https://channelmyanmar.org/mission-mangal2019/",
  },
  {
    "id": "28",
    "image": "https://image.tmdb.org/t/p/w185/uLE57OZPq9opQJhkHfijkSpCkVQ.jpg",
    "title": "Raatchasi (2019)",
    "type": "Drama",
    "cast": {
              "director": "Sy Gowtham Raj",
              "actor": "Akalya Venkatesan",
              "actress": "Arul Dass",
            },
    "synopsis": "Raatchasi (2019) is a thought-provoking and socially relevant Tamil drama that sheds light on the challenges faced by the education system in rural India. Jyothika delivers a powerful performance as a determined and passionate schoolteacher who takes on the corrupt bureaucracy to bring positive change to a struggling school. The film highlights issues like educational disparity, societal norms, and the importance of quality education. While the narrative might feel predictable at times, the film's strong message and Jyothika's compelling portrayal make it a compelling watch. Director Sy. Gowthamraj effectively creates a blend of emotional moments and impactful dialogues, urging viewers to reflect on the state of education in marginalized communities. Raatchasi is a film that addresses pertinent issues while keeping the audience engaged with its engaging storytelling and compelling lead performance.",
    "rating": "7",
    "trailer": "https://youtu.be/mC9e7ywzvnU",
    "url": "https://channelmyanmar.org/raatchasi-2019/",
  },
  {
    "id": "29",
    "image": "https://channelmyanmar.org/wp-content/uploads/2021/11/MV5BOTg0OWVmOGEtZjhiOS00N2IxLWJiNDMtYmJkYTQyMmY5YzQyXkEyXkFqcGdeQXVyNTgxODY5ODI@._V1_.jpg",
    "title": "Adbhutham (2021)",
    "type": "Bollywood, Romance, Sci-Fi",
    "cast": {
              "director": "unknow",
              "actor": "Devi Prasad",
              "actress": "Mandava Sai Kumar",
            },
    "synopsis": "Adbhutham 2021 is a visually stunning and thought-provoking movie that takes the audience on a captivating journey. The film successfully blends elements of fantasy, suspense, and mystery to create a unique cinematic experience. The story is engaging, with well-developed characters and unexpected plot twists that keep the viewers on the edge of their seats. The cinematography is breathtaking, with beautiful landscapes and stunning visual effects that enhance the overall storytelling. The performances by the cast are commendable, bringing depth and emotion to their respective roles. The movie seamlessly explores themes of magic, destiny, and the power of human connection. Adbhutham 2021 is an enriching film that promises to leave audiences both entertained and inspired.",
    "rating": "8",
    "trailer": "https://youtu.be/3lLD-TJZBNc",
    "url": "https://channelmyanmar.org/adbhutham-2021/",
  },
]